# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/zuche
    username: root
    password: xxxxxx
    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/templates
    request-context-attribute: request

  redis:
    host: 192.168.0.108
    port: 6379
#    host: 172.29.15.102

wechat:
  mpAppId: wx50ef023ba49d5680
  mpAppSecret: 3e60ffe4d08baa96edbc713d47a7dfc3
  openAppId: xxxxxx
  openAppSecret: xxxxxxxxxxxxxxxxxxxx
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sig.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: 9R4Syxmh4RHf8IvFxxX1KJTxqCW_2DYIUPGs7AXi-oE

project-url:
  wechatMpAuthorize: http://sig.natapp1.cc
  wechatOpenAuthorize: http://sig.natapp1.cc
  sell: http://localhost:8080
#  sell: http://sig.natapp1.cc

upyun:
  username: late0001
  password: vZOzbVzB3eWozYXgW8CsZ9Y0ZWhODzEZ
  imageHost: http://image-site001.test.upcdn.net

#  jackson:
#    default-property-inclusion: non_null
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    name: d:/hello.log
#  level:
#    com.chifan.demo.LoggerTest: debug
logging:
  level:
    com.chifan.demo.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml